/* AUTO-GENERATED — do not edit. Run: python backend/scripts/generate_demo_profiles.py */
export const DEMO_PROFILES = [
  {
    "id": "user-1289958",
    "name": "Клиент 15k",
    "sourceUserId": 1289958,
    "targetMonthlyIncomeRub": 15000,
    "monthlyIncomeRub": 15003,
    "incomeQuantile": 0.0006,
    "age": 24,
    "balance": 5250.97,
    "balanceSource": "income_share_proxy",
    "sex": 0,
    "sexLabel": "Женщина",
    "seniorityMonths": 21,
    "isNewCustomer": 0,
    "segment": "STUDENTS",
    "regionName": "ZAMORA",
    "ownedProducts": [
      "card-2"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 1,
      "dep-5": 0,
      "card-1": 0,
      "card-5": 0,
      "rko-2": 0,
      "rko-3": 0,
      "rko-4": 0,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 0,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 0,
      "loan-5": 0,
      "biz-4": 0,
      "dep-6": 0,
      "loan-4": 0,
      "card-3": 0
    },
    "info": "Студент",
    "description": "Реальный клиент из датасета  выбранный рядом с уровнем дохода 15 000 ₽/мес.",
    "characteristics": [
      "Стартовый доход",
      "Профиль из реального датасета"
    ],
    "scoringIncome": 15002.76
  },
  {
    "id": "user-649589",
    "name": "Клиент 100k",
    "sourceUserId": 649589,
    "targetMonthlyIncomeRub": 100000,
    "monthlyIncomeRub": 100000,
    "incomeQuantile": 0.4953,
    "age": 55,
    "balance": 35000.03,
    "balanceSource": "income_share_proxy",
    "sex": 1,
    "sexLabel": "Мужчина",
    "seniorityMonths": 115,
    "isNewCustomer": 0,
    "segment": "INDIVIDUALS",
    "regionName": "SEVILLA",
    "ownedProducts": [
      "card-2"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 1,
      "dep-5": 0,
      "card-1": 0,
      "card-5": 0,
      "rko-2": 0,
      "rko-3": 0,
      "rko-4": 0,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 0,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 0,
      "loan-5": 0,
      "biz-4": 0,
      "dep-6": 0,
      "loan-4": 0,
      "card-3": 0
    },
    "info": "Частный клиент",
    "description": "Реальный клиент из датасета  выбранный рядом с уровнем дохода 100 000 ₽/мес.",
    "characteristics": [
      "Стабильный доход",
      "Профиль из реального датасета"
    ],
    "scoringIncome": 100000.08
  },
  {
    "id": "user-1125781",
    "name": "Клиент 500k",
    "sourceUserId": 1125781,
    "targetMonthlyIncomeRub": 500000,
    "monthlyIncomeRub": 499979,
    "incomeQuantile": 0.9901,
    "age": 23,
    "balance": 174992.54,
    "balanceSource": "income_share_proxy",
    "sex": 1,
    "sexLabel": "Мужчина",
    "seniorityMonths": 38,
    "isNewCustomer": 0,
    "segment": "INDIVIDUALS",
    "regionName": "CANTABRIA",
    "ownedProducts": [
      "card-2",
      "rko-1"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 1,
      "dep-5": 0,
      "card-1": 0,
      "card-5": 0,
      "rko-2": 0,
      "rko-3": 0,
      "rko-4": 0,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 1,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 0,
      "loan-5": 0,
      "biz-4": 0,
      "dep-6": 0,
      "loan-4": 0,
      "card-3": 0
    },
    "info": "Частный клиент",
    "description": "Реальный клиент из датасета  выбранный рядом с уровнем дохода 500 000 ₽/мес.",
    "characteristics": [
      "Стабильный доход",
      "Есть бизнес-продукты",
      "Профиль из реального датасета"
    ],
    "scoringIncome": 499978.68
  },
  {
    "id": "user-167364",
    "name": "Клиент 5000k",
    "sourceUserId": 167364,
    "targetMonthlyIncomeRub": 5000000,
    "monthlyIncomeRub": 5046790,
    "incomeQuantile": 0.9998,
    "age": 70,
    "balance": 1766376.66,
    "balanceSource": "income_share_proxy",
    "sex": 1,
    "sexLabel": "Мужчина",
    "seniorityMonths": 194,
    "isNewCustomer": 0,
    "segment": "INDIVIDUALS",
    "regionName": "MADRID",
    "ownedProducts": [
      "card-2",
      "rko-4",
      "srv-3"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 1,
      "dep-5": 0,
      "card-1": 0,
      "card-5": 0,
      "rko-2": 0,
      "rko-3": 0,
      "rko-4": 1,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 0,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 1,
      "loan-5": 0,
      "biz-4": 0,
      "dep-6": 0,
      "loan-4": 0,
      "card-3": 0
    },
    "info": "Частный клиент",
    "description": "Реальный клиент из датасета  выбранный рядом с уровнем дохода 5 000 000 ₽/мес.",
    "characteristics": [
      "Высокий доход",
      "Есть бизнес-продукты",
      "Профиль из реального датасета"
    ],
    "scoringIncome": 5046790.47
  }
] as const
