#!/usr/bin/env node
/**
 * Сервер на ПК + модель в Expo + установка на телефон.
 *
 *   node scripts/phone.mjs              # API + export + expo run:android (USB)
 *   node scripts/phone.mjs --expo-go    # API + export + Expo Go (QR в терминале)
 *   node scripts/phone.mjs --server-only  # только API :8000
 *   node scripts/phone.mjs --no-install   # API + модель, без сборки APK
 */

import { spawn, spawnSync } from 'node:child_process'
import { networkInterfaces } from 'node:os'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const frontend = join(root, 'frontend')
const mobile = join(root, 'mobile')
const isWin = process.platform === 'win32'

const args = new Set(process.argv.slice(2))
const expoGo = args.has('--expo-go')
const serverOnly = args.has('--server-only')
const noInstall = args.has('--no-install')

const MODEL_REQUIRED = ['catboost_pointwise.cbm', 'catboost_model.json', 'feature_order.json']

function log(msg) {
  console.log(`\n▶ ${msg}`)
}

function fail(msg) {
  console.error(`\n✖ ${msg}`)
  process.exit(1)
}

function run(cmd, cmdArgs, opts = {}) {
  const r = spawnSync(cmd, cmdArgs, {
    cwd: opts.cwd ?? root,
    stdio: 'inherit',
    shell: isWin,
    env: { ...process.env, ...opts.env },
  })
  if (r.status !== 0) process.exit(r.status ?? 1)
}

function detectLanIp() {
  const candidates = []
  for (const name of Object.keys(networkInterfaces())) {
    if (/vmware|virtual|vethernet|loopback/i.test(name)) continue
    for (const net of networkInterfaces()[name] ?? []) {
      if (net.family !== 'IPv4' || net.internal) continue
      if (!net.address.startsWith('192.168.') && !net.address.startsWith('10.')) continue
      candidates.push({ name, address: net.address })
    }
  }
  if (candidates.length === 0) {
    fail('Не найден Wi‑Fi/LAN IPv4. Подключите ПК и телефон к одной сети.')
  }
  const wifi = candidates.find((c) => /wi-?fi|wlan|беспровод/i.test(c.name))
  return (wifi ?? candidates[0]).address
}

function exportModelBundle() {
  log('Экспорт модели (train → frontend/public/model → mobile/assets/model)…')
  run('python', [join(root, 'backend', 'scripts', 'export_model.py')])
}

function verifyModelBundle() {
  run('node', [join(root, 'scripts', 'verify-model.mjs')])
}

function writeEnvFiles(ip) {
  const apiUrl = `http://${ip}:8000/api`
  const lines = [
    `# Auto-generated by scripts/phone.mjs`,
    `EXPO_PUBLIC_API_BASE_URL=${apiUrl}`,
    `EXPO_PUBLIC_USE_MOCK=false`,
    `EXPO_PUBLIC_USE_LOCAL_MODEL=true`,
    '',
  ].join('\n')

  writeFileSync(join(mobile, '.env'), lines, 'utf8')

  const feEnv = [
    `# Auto-generated by scripts/phone.mjs`,
    `VITE_API_BASE_URL=${apiUrl}`,
    `VITE_USE_MOCK=false`,
    `VITE_USE_LOCAL_MODEL=true`,
    '',
  ].join('\n')
  writeFileSync(join(frontend, '.env.local'), feEnv, 'utf8')

  mkdirSync(join(frontend, 'public'), { recursive: true })
  writeFileSync(
    join(frontend, 'public', 'dev-server.json'),
    JSON.stringify({ apiUrl, host: ip, generatedAt: new Date().toISOString() }, null, 2),
    'utf8',
  )

  log(`API для телефона: ${apiUrl}`)
}

function startServer(ip) {
  const apiReq = join(root, 'backend', 'requirements-api.txt')
  log('Зависимости API…')
  run('python', ['-m', 'pip', 'install', '-q', '-r', apiReq])

  log(`API http://${ip}:8000 (0.0.0.0)…`)
  return spawn(
    'python',
    ['-m', 'uvicorn', 'src.api.server:app', '--host', '0.0.0.0', '--port', '8000'],
    {
      cwd: join(root, 'backend'),
      stdio: 'inherit',
      shell: isWin,
      env: process.env,
    },
  )
}

async function waitForServer() {
  const url = 'http://127.0.0.1:8000/api/health'
  for (let i = 0; i < 40; i++) {
    try {
      const res = await fetch(url)
      if (res.ok) return true
    } catch {
      /* not ready */
    }
    await new Promise((r) => setTimeout(r, 500))
  }
  return false
}

function findAdb() {
  if (process.env.ADB) return process.env.ADB
  const candidates = isWin
    ? [join(process.env.LOCALAPPDATA || '', 'Android', 'Sdk', 'platform-tools', 'adb.exe')]
    : [join(process.env.HOME || '', 'Library', 'Android', 'sdk', 'platform-tools', 'adb')]
  for (const p of candidates) {
    if (p && existsSync(p)) return p
  }
  return 'adb'
}

function hasUsbDevice() {
  const adb = findAdb()
  const r = spawnSync(adb, ['devices'], { encoding: 'utf8', shell: isWin })
  if (r.status !== 0) return false
  return (r.stdout || '').split('\n').some((l) => l.includes('\tdevice'))
}

function ensureMobileDeps() {
  if (!existsSync(join(mobile, 'node_modules'))) {
    log('npm install в mobile/…')
    run('npm', ['install'], { cwd: mobile })
  }
}

async function main() {
  const ip = detectLanIp()
  log(`IP в сети: ${ip}`)

  writeEnvFiles(ip)
  const serverProc = startServer(ip)

  if (!(await waitForServer())) {
    serverProc.kill()
    fail('API не ответил на :8000')
  }
  log('API ✓')

  if (serverOnly) {
    log('Режим --server-only. Ctrl+C — остановка.')
    await new Promise(() => {})
    return
  }

  exportModelBundle()
  verifyModelBundle()
  ensureMobileDeps()

  if (expoGo) {
    log('Expo Go: установите «Expo Go» из Play Store, отсканируйте QR.')
    log('Модель CatBoost уже в bundle (mobile/assets/model).')
    run('npx', ['expo', 'start', '--lan'], {
      cwd: mobile,
      env: { EXPO_PUBLIC_API_BASE_URL: `http://${ip}:8000/api` },
    })
    return
  }

  if (noInstall) {
    log('Модель и .env готовы. Сборка: cd mobile && npx expo run:android')
    log('Ctrl+C — остановка API.')
  } else if (!hasUsbDevice()) {
    log('USB-устройство не найдено. Запускаю Expo Go (QR)…')
    run('npx', ['expo', 'start', '--lan'], { cwd: mobile })
    return
  } else {
    log('Сборка и установка debug APK (expo run:android)…')
    log('Первая сборка может занять 10–20 минут.')
    run('npx', ['expo', 'run:android', '--device'], {
      cwd: mobile,
      env: {
        EXPO_PUBLIC_API_BASE_URL: `http://${ip}:8000/api`,
        EXPO_PUBLIC_USE_MOCK: 'false',
        EXPO_PUBLIC_USE_LOCAL_MODEL: 'true',
      },
    })
    log('Приложение установлено. ПК и телефон — одна Wi‑Fi.')
  }

  await new Promise((resolve) => {
    const stop = () => {
      serverProc.kill()
      resolve()
    }
    process.on('SIGINT', stop)
    process.on('SIGTERM', stop)
    serverProc.on('exit', resolve)
  })
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
